export const scooters = [
  {
    id: 1,
    image: "orange-moto.webp",
    code: "bg-[#E36029]",
    price: "$29/day",
    name: "Arancio Impulsivo",
    type: "scooter",
  },
  {
    id: 2,
    image: "white-moto.webp",
    code: "bg-[#E1E2E2]",
    price: "$29/day",
    name: "Bianco Innocente",
    type: "scooter",
  },
  {
    id: 3,
    image: "green-moto.webp",
    code: "bg-[#BED0C5]",
    price: "$29/day",
    name: "Verde Amabile",
    type: "scooter",
  },
  {
    id: 4,
    image: "blue-moto.webp",
    code: "bg-[#2C3E62]",
    price: "$29/day",
    name: "Blu Energico Matt",
    type: "scooter",
  },
  {
    id: 5,
    image: "black-moto.webp",
    code: "bg-[#1A1A1A]",
    price: "$29/day",
    name: "Nero Convinto",
    type: "scooter",
  },
];
