export const tours = [
  {
    id: 1,
    title: "Palmeraie Vespa Escape",
    image: "tour1.webp",
    duration: "2 hours",
    highlights: [
      "Explore the Palmeraie palm grove",
      "Ride along desert trails",
      "Visit a traditional Berber home",
      "Enjoy Moroccan mint tea with locals",
    ],
    price: 250,
    minPeople: 2,
    featured: true,
    rating: 4.9,
  },
  {
    id: 2,
    title: "Marrakech Sunset Ride",
    image: "tour3.webp",
    duration: "2 hours",
    highlights: [
      "Cruise through the Red City's outskirts",
      "Catch stunning sunset views over the city",
      "Photo stops at scenic spots",
      "Light Moroccan snacks and tea included",
    ],
    price: 250,
    minPeople: 2,
    featured: false,
    rating: 4.8,
  },
  {
    id: 3,
    title: "Cultural Medina Tour",
    image: "tour2.webp",
    duration: "2 hours",
    highlights: [
      "Ride through the historic Medina alleys",
      "Stop at hidden riads and artisan shops",
      "Traditional Moroccan lunch included",
      "Local guide sharing stories & legends",
    ],
    price: 250,
    minPeople: 2,
    featured: false,
    rating: 4.9,
  },
  {
    id: 4,
    title: "The Seven Saints Tour of Marrakech",
    image: "tour4.webp",
    duration: "3 hours",
    highlights: [
      "Discover the story of the Seven Saints of Marrakech",
      "Ride through the old medina on a Vespa",
      "Visit historical mausoleums and spiritual sites",
      "Learn about local legends and traditions from your guide",
    ],
    price: 250,
    maxPeople: 2,
    featured: true,
    rating: 4.8,
  },
];
